name: "CI/CD Pipeline"

on:
  push:
    branches:
      - 'main'
      - 'release/**'

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout (PR)
        uses: actions/checkout@v3
        if: github.event_name == 'pull_request'
        with:
          ref: ${{ github.event.pull_request.head.ref }}
          fetch-depth: 0

      - name: Checkout (Push)
        uses: actions/checkout@v3
        if: github.event_name == 'push'
        with:
          fetch-depth: 0

      - name: Set application version
        if: github.event_name == 'push'
        id: set_version
        uses: kvendingoldo/semver-action@v1.15
        with:
          primary_branch: main
          enable_github_releases: true
          github_token: "${{ secrets.GH_TOKEN }}"
          init_version: rc/0.1.0
